### ISSUE TITLE
Error in export_summs when exporting table to docx with more than one regression model and error_pos = "right"

### ISSUE THREAD

**Issue by haoxue-fan** [jacob-long/jtools#102]
I recently discovered this package and it has been super helpful to me! However, I have encountered a problem when I tried to export more than one model to .docx using export_summs. It seems that when error_pos = "right" it generates the error `duplicated col_keys`. This doesnt happen when error pos is below/same, or generating a .html table.

I have tried to use the version from GitHub, but it doesnt help. 

This bug can be reproduced by modifying the example in the export_summs:

export_summs(fit1, fit2, error_pos = "right", to.file = "docx", file.name = "test.docs")
Error in flextable::flextable(cc) : duplicated col_keys

Thank you in advance!

**Comment by jacob-long** [comment]
This appears to be a bug originating in the `huxtable` package. I have reported it to that package's author: https://github.com/hughjonesd/huxtable/issues/222

**Comment by jacob-long** [comment]
The next release of `huxtable` will include a fix for this.
