### ISSUE TITLE
Removing NA Fixed Effects in plot_summs

### ISSUE THREAD

**Issue by ECon87** [jacob-long/jtools#103]
**Is your feature request related to a problem? Please describe.**

I run a regression with multiple fixed effects using `as_factor(fe.Var)` but one of them is dropped (I excluded the intercept).
I thought the `plot_coefs` method would work if I defined a `broom::tidy` object (removing NA) but it didn't.

**Describe the solution you'd like**

An option that allows NA rows. I get error that the existing and assigned data don't match. An option in the plot_summs method would be nice.

**Describe any alternatives or other implementations that you might know of**

I could  parse out the fixed effects and re-run the model. But I wish to avoid the extra step.

Thanks.

**Comment by jacob-long** [comment]
I was thinking it wouldn't have any NA in this scenario. Do you have a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)?
