### ISSUE TITLE
Can't apply summ in rq model

### ISSUE THREAD

**Issue by hikmatulislmyh** [jacob-long/jtools#105]
<!--Please briefly describe your problem and what output you expect.

I can't apply summ() in quantile regression. but when installing, there is summ.rq
I install jtools from github because I hope I can use an update package.
Please help me. Thank you

* installing *source* package 'jtools' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'jtools'
    finding HTML links ... done
    center                                  html  
    center_mod                              html  
    effect_plot                             html  
    export_summs                            html  
    get_colors                              html  
    get_formula                             html  
    get_robust_se                           html  
    glance.summ                             html  
    gridlines                               html  
    gscale                                  html  
    interactions_deprecated                 html  
    jtools_colors                           html  
    knit_print.summ                         html  
    make_new_data                           html  
    make_predictions                        html  
    md_table                                html  
    model_utils                             html  
    movies                                  html  
    nin                                     html  
    num_print                               html  
    partialize                              html  
    pf_sv_test                              html  
    plot_summs                              html  
    predict_merMod                          html  
    reexports                               html  
    scale_mod                               html  
    set_summ_defaults                       html  
    standardize                             html  
    subsetters                              html  
    summ                                    html  
    summ.glm                                html  
    summ.lm                                 html  
    summ.merMod                             html  
    summ.rq                                 html  
    summ.svyglm                             html  
    svycor                                  html  
    svysd                                   html  
    theme_apa                               html  
    theme_nice                              html  
    weights_tests                           html  
    wgttest                                 html  
    wrap_str                                html  
    wtd.sd                                  html  
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (jtools)

Error in UseMethod("summ") : 
  no applicable method for 'summ' applied to an object of class "rqs

**Comment by jacob-long** [comment]
Hi there, I'll need some more info to address this. I test the package with some rq models without any issues so I need to see what kind of issue you're dealing with in order to troubleshoot.
