### ISSUE TITLE
error when trying to run plot_summs()

### ISSUE THREAD

**Issue by suncatx** [jacob-long/jtools#107]
Thanks for developing this package it is fab - I just wish these plots would work for me. 

I've tried running it at the most basic level of plot_summs(model) and this is the error I get, which seems to be related to the source code maybe?: 

Loading required namespace: broom.mixed
Failed with error:  ‘there is no package called ‘broom.mixed’’
Error in UseMethod("tidy") : 
  no applicable method for 'tidy' applied to an object of class "c('negbin', 'glm', 'lm')"

```

**Comment by thewallstands** [comment]
Please install the package using install.packages("broom.mixed)
