### ISSUE TITLE
Error in export_summs knitting to pdf 

### ISSUE THREAD

**Issue by theloniousgoerz** [jacob-long/jtools#108]
I am making a regression table with the export_summs function and for some reason it will not knit to pdf even when the results are set to "asis". I am not sure if this is a bug or if someone has some clarity on the issue?

```r
## reproducible example, code chunk set results = "asis"
export_summs(lm(lifeExp ~ pop, data = gapminder:: gapminder))
```

**Comment by ehsong** [comment]
I'm having the same issue - I can't knit regression results to pdf

**Comment by jacob-long** [comment]
I cannot replicate this issue.

Using the following .Rmd

````rmarkdown
---
title: "test"
author: "Jacob Long"
date: '2022-04-07'
output: 
  pdf_document:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(jtools)
export_summs(lm(lifeExp ~ pop, data = gapminder:: gapminder))
```
````

I get the following output: [test.pdf](https://github.com/jacob-long/jtools/files/8447189/test.pdf)

I did need to update my TeX installation first, though.
