### ISSUE TITLE
glmmTMB and partial residuals - work around?

### ISSUE THREAD

**Issue by elliotjohnston** [jacob-long/jtools#115]
Hi Jacob,

I found your 'Visualizing regression model predictions' vignette really helpful in understanding how to shift raw data to account for the effect of covariates. I am working with the cat_plot function in the interactions package and trying to set partial.residuals = TRUE with a glmmTMB model. I have searched old issues here and I know this has been highlighted before, so I don't mean to rehash old topics. It appears that support has not since been added for glmmTMB models, given that I get the error: match.arg(type) : 'arg' should be one of “response”, “pearson”.

I am looking for any insights and/or code you could suggest for manually adjusting raw count data for the effect of two continuous covariates to plot alongside the visualization of a glmmTMB model (plotting categorical by categorical interaction). I don't have a good sense for what partial.residuals = TRUE is doing under the hood with other model types. I have written up a full post with sample code and graphs at: https://stats.stackexchange.com/questions/543996/shifting-raw-count-data-for-covariate-effects-in-glmmtmb. Even if you do not have the bandwidth for a full solution, any ideas on which direction to head would be very much appreciated!

-Elliot

**Comment by lionel68** [comment]
The function fails because there is no method implemented for working residuals in glmmTMB object, I opened an [issue](https://github.com/glmmTMB/glmmTMB/issues/776) at the glmmTMB github repo on this.

**Comment by jacob-long** [comment]
Okay, from what I can tell, @lionel68's issue being resolved over at glmmTMB has fixed the problem. If I'm wrong, please comment and I'll reopen the issue.
