### ISSUE TITLE
broom.mixed getting fussier about unused arguments in ...

### ISSUE THREAD

**Issue by bbolker** [jacob-long/jtools#119]
Hi,

I am trying to submit a new version of `broom.mixed` to CRAN.

https://github.com/bbolker/broom.mixed/commit/8423ebd8bf7178636fefc81aca6810285c1df3bd

added a call to `brmsfit` that throws an error if there are unused values in `...`. In this case you have generic `intervals` and `prob` arguments (meant for `lme` objects??), and `par_types` (which isn't used by `broom.mixed` at the moment).

  I will revert this test for now, but it would be good to adjust this if possible ...

(I'm not sure this counts as a bug, but I don't seem to be able to un-label it ...)

**Comment by jacob-long** [comment]
Thanks Ben, I think I've removed this behavior in my dev branch. As best as I can tell, those arguments were holdovers from the non-standard arguments that `broom::tidy.brmsfit` used to look for.
