### ISSUE TITLE
Can't install latest jtools for R 3.6.3.

### ISSUE THREAD

**Issue by hummelrichard** [jacob-long/jtools#126]
When installing jtools using install.packages("jtools"), install fails. I believe it is because the R dependency is written as 3.50, which is interpreted (I think) as 3.50.0, and so R reports that my version is too low. I was able to install jtools by manually modifying the R version requirement in the DESCRIPTION file.

```r
install.packages("jtools")
```

**Comment by jacob-long** [comment]
Oops, thanks for reporting that! I'll post a fix to Github momentarily and to CRAN in a few days.
