### ISSUE TITLE
Only show MODEL INFO and MODEL FIT without estimates

### ISSUE THREAD

**Issue by Marcelara** [jacob-long/jtools#129]
Hello!

This might be a very basic question and I'm new to GitHub so apologies in advance if I'm missing information; 

is there a way to only show the MODEL INFO and MODEL FIT sections without printing all the list of coefficients? Something like `summ(model, coefficients=FALSE)`?

I'm comparing many different models and for now, I would like to only have the Info summaries so I can have a better overview without all the information from the coefficients

Many thanks!

**Comment by jacob-long** [comment]
Good idea! Done.
