### ISSUE TITLE
users of scale = T likely assume this scales the outcome also

### ISSUE THREAD

**Issue by tbates** [jacob-long/jtools#131]
**Problem**
Students use scale and assume that this scales the outcome (when it only scales the `rhs`).

The problem is that the standardized coefficients are then interpreted as what an SD of x causes in SD of y,  but the output is actually in raw units of y. I can't see a conventional use for scaling x without scaling y...

**Solution you'd like**
It would be nice to wind back time and have `transform.response` default to TRUE. But perhaps the output notification could say:

> Continuous predictors are mean-centered and scaled by 1 s.d (the output remains in raw units)

i.e., notify users when y is raw. Otherwise they are reporting scaled effects often way bigger than the expected beta.

**Comment by jacob-long** [comment]
Yes, I'm open to being more explicit that the outcome is not being transformed when it is not. The current wording says nothing about the outcome and so I can see how any user who might be expecting the outcome to be scaled not getting that information from the current message.
