### ISSUE TITLE
plot_summs error

### ISSUE THREAD

**Issue by calzadillan** [jacob-long/jtools#134]
Hi there, I'm trying to use plot_summs. Here is my code. 

```r
met1<-lm(fibrosis ~ age + bmi + auditc +sex+ `cis-3,4-methyleneheptanoylglycine`, data=mlr)
library(jtools)
library(huxtable)
library(officer)
library(flextable)
library(broom.mixed)
plot_summs(met1)
```

And I get this error:
Error in element_line(colour = text_and_line_color, linewidth = 0.5, linetype = 1,  : 
  unused argument (linewidth = 0.5)
In addition: Warning messages:
1: Ignoring unknown parameters: linewidth 
2: Ignoring unknown parameters: linewidth 

Any assistance is appreciated. Thanks!

**Comment by geejaytee** [comment]
This is also true for running effect_plot() on R 4.2.1, package version 2.2.1

But the issue arose when installing the package:
`** byte-compile and prepare package for lazy loading`
`Note: possible error in 'element_line(colour = text_and_line_color, ': unused argument (linewidth = 0.5)`
`Note: possible error in 'element_line(colour = text_and_line_color, ': unused argument (linewidth = 0.5)`
`Note: possible error in 'element_rect(fill = bg_color, ': unused argument (linewidth = 0.5)`

**Comment by jacob-long** [comment]
Hi there, this problem should be fixed if you update to the latest edition of the `ggplot2` package.
