### ISSUE TITLE
Can't get chunk option render='normal_print' to work, in a Quarto revealjs presentation

### ISSUE THREAD

**Issue by jhchou** [jacob-long/jtools#145]
I installed `jtools` to display logistic regression model output from `glm` in a Quarto `revealjs` presentation. The initial `summ()` output was the "plain text" version.

I then installed `kableExtra` and the `summ()` output was prettified, but took up too much space.

I tried using the chunk option `{r, render='normal_print'}`, but the output remained prettified.

I also tried setting `knitr` global chunk options as in your repo:

```
knitr::opts_chunk$set(
  render = knitr::normal_print,
)
library(jtools)
```

... also unsuccessfully at getting back to plain text output. Am I doing something wrong?

**Comment by jacob-long** [comment]
I believe if you set the option `"summ-normal-print"` to `TRUE`, you should get equivalent output as if you didn't have `kableExtra` installed.

So sticking this code somewhere should fix it, if I'm not mistaken:

```r
options("summ-normal-print", TRUE)
```
