### ISSUE TITLE
apa_theme top border missing with facet_wrap

### ISSUE THREAD

**Issue by victorhartman** [jacob-long/jtools#152]
The top border is missing when using facet_wrap in combination with theme_apa. Facet_grid works as expected

```r
library(ggplot2)

p <- ggplot(mpg, aes(displ, hwy)) + geom_point()

p + facet_wrap(vars(class)) + 
  jtools::theme_apa()
```

**Comment by jacob-long** [comment]
Hi @victorhartman, thanks for the report! I'm not totally clear on what's missing. Just for reference, here's the output I'm currently getting:

![image](https://github.com/user-attachments/assets/df26b1ec-14de-4b7c-9bcd-c440bd812562)

And when I check out your pull request and re-run the code, I'm getting what I think is an identical output:

![image](https://github.com/user-attachments/assets/6c7eb06c-91a5-4af6-81a5-8ad992ff9cd0)

I wonder if maybe there's a `ggplot2` version issue or something?
