### ISSUE TITLE
changing the range of x-axis in plot_summs 

### ISSUE THREAD

**Issue by sunyixian** [jacob-long/jtools#18]
Dear all,

I'm new to jtools, but really like this package. I'm wondering if we set by ourselves the range of x-axis when we use plot_summs to report our regression results. We have results for two different samples, but would like to compare them visually, so it would be great if the two plots can have the same scale on the x-axis. Is there any way to do it? If not, any other packages can do such things? Thanks!

**Comment by jacob-long** [comment]
If I understand the problem correctly, I think this should be easy to do.

For example, we have a model like this:

```r
fit <- lm(formula = mpg ~ vs * am, data = mtcars)
```

And when you use `plot_summs` (`plot_summs(fit)`), in this case the x axis ranges from around -2 to 10. If I wanted to widen the range to go from -5 to 15, I'd use `ggplot2`'s `xlim` function. Here's an example:

```r
library(ggplot2)
plot_summs(fit) + xlim(-5, 15)
```

However, I would also make a second suggestion. `plot_summs` was designed for the very problem you're facing — comparing two models with some/all the same predictors. To plot both estimates in the **same plot**, you can provide them both to `plot_summs` like this:

```r
plot_summs(fit1, fit2)
```

And it will show the two results for both models with the estimates right next to each other.

**Comment by sunyixian** [comment]
This is very helpful, thank you so much!
