### ISSUE TITLE
Support for quantreg package

### ISSUE THREAD

**Issue by mattmoo** [jacob-long/jtools#19]
Fantastic package, I was wondering how much wrangling would be needed to support quantile regression models generated by the `quantreg` package?

The output is in a very similar format to the `stats` regression functions, but there's obviously something stopping it from getting all the way:

```
library(quantreg)
library(jtools)

qrModel = rq(Income ~ Frost + Illiteracy + Murder, data = as.data.frame(state.x77))

summ(qrModel)

Error in `[.data.frame`(coefs, , c("std.error", "statistic", "p.value")) : 
  undefined columns selected
Error in summ.default(qrModel) : 
  Could not find a way to extract coefficients via broom::tidy or coeftest.
```

**Comment by jacob-long** [comment]
This should certainly be doable. I've decided to abandon the default `summ` method in the upcoming version of `jtools`, which is what is failing to handle the `qr` model in your example here. As you can see, it's hard to write a function with complex output when you don't know what input it will get. Support for `qr` objects would just require a new `summ.qr` method.

I've outlined a few things in issue #16 that I would like to factor in when deciding whether to support a new model type. I think the quantile regression models meet most of those criteria — the open question is how `summ` can add some value to the default `summary` method. What do you think?

Things I can do based on a few minutes of testing:

* Produce SEs, t-statistics, p-values, and confidence intervals
* Use `quantreg`'s built-in abilities for calculating robust SEs
* Rescale/mean-center predictors (though one wonders whether mean-centering makes sense for quantile regression). 
* Basic information about the model (DV, number of observations, tau parameter)

What I'm not sure about is model fit indices, in particular what sort of model fit indices — if any — would be appropriate for quantile regressions.

**Comment by jacob-long** [comment]
Thanks for this, that's helpful — as a package developer, you don't get that much information about what people are using the package for except when things break.

There are some serious quirks with `quantreg`, but I've built out some nice support for it on my dev branch. I'll ping this issue again when I've pushed it and you can take a look.

**Comment by jacob-long** [comment]
Things should be working pretty well with the latest development version here on GitHub. Let me know if you have any issues/frustrations/etc.

**Comment by mattmoo** [comment]
Thanks heaps Jacob, can't wait to try it out!
