### ISSUE TITLE
Clustered Standard Errors

### ISSUE THREAD

**Issue by ericmak2607** [jacob-long/jtools#21]
I am using the interact_plot function. I wish to use clustered standard errors (or other alternative standard errors in general), rather than the default SE in the "lm" function, in computing the confidence intervals. Is this doable?

**Comment by jacob-long** [comment]
This is doable! Check out the latest development version of the package by downloading from Github:

```r
devtools::install_github("jacob-long/jtools")
```

Usage is documented at `?interact_plot` with the arguments `robust` and `cluster`. You can use standard error calculations from a package other than `sandwich` by providing the variance-covariance matrix to the `vcov` argument instead. This is a new feature so please let me know if you run into any issues or output that doesn't make sense.
