### ISSUE TITLE
Unexpected behaviour writing plot_summs to PDF

### ISSUE THREAD

**Issue by mattmoo** [jacob-long/jtools#29]
I seem to be unable to write plot_summs to PDF in a similar way to how I did pre-1.0

The following works when copy and pasted into the command line, but when run from a script seems to return an empty file.

```
states <- as.data.frame(state.x77)
fit1 <- lm(Income ~ Frost, data = states)
pdf('test.pdf')
plot_summs(fit1)
dev.off()
```

**Comment by jacob-long** [comment]
I'm not sure what to make of this. Does this happen with other plots from `ggplot2`?

**Comment by mattmoo** [comment]
Works fine with other `ggplot2` plots.

**Comment by jacob-long** [comment]
I'm not replicating this on my machine. There could be a few reasons:

* `ggplot`'s latest update.
* R updates (not sure if `3.5` was out when you created the issue)
* My machine (macOS High Sierra) being different from yours in some other way.
