### ISSUE TITLE
lmer output

### ISSUE THREAD

**Issue by rtxj89** [jacob-long/jtools#30]
Hi there! 

Just saw your package today and have been really enjoying it. I use lmer (from lme4), and the only way I can get summ() to output is if I put "pvals=FALSE". Is there any way you could implement P values into the output (perhaps in the same vein as lmerTest)? Thanks again, this is an amazing package!

Adam

**Comment by jacob-long** [comment]
Thanks for the feedback!

Let me clarify the issue since I'm not 100% sure what is going on — you should always get some output. What exactly happens when you do not have `pvals = FALSE`? The function runs but you get no output?

**Comment by jacob-long** [comment]
Thanks for these details, this is definitely a bug. For now, you can get Kenward-Roger standard errors if you have the `pbkrtest` package installed. Right now the function isn't handling the absence of that package gracefully like it should.
