### ISSUE TITLE
Rename Facets in 3 Way Interactions

### ISSUE THREAD

**Issue by krcarriere** [jacob-long/jtools#31]
Is there a way to rename the facets of interact_plot? 

data <- mtcars
model3<- lm(data=data, mpg ~ wt * hp  *  drat)
jtools::interact_plot(model3, pred = "wt",
                      modx = "hp", mod2="drat", jnplot="true",
                      x.label="X Label", y.label="Y Label",
                      legend.main="Legend Title")

It's kind of clunky to have it say "Mean of drat - 1 SD" "Mean of drat" "Mean of drat + 1 SD"
![example](https://user-images.githubusercontent.com/11062961/40316004-f00ccd36-5cea-11e8-8af3-eb4cdeadfa97.png)

Also - at least for me, trying to add : mod2.labels=c("Test1", "Test2", "Test3") doesn't help.

**Comment by jacob-long** [comment]
This is a bug. I think using `mod2.labels` without also specifying `mod2vals` causes `mod2.labels` to be ignored. I should be able to fix this shortly.

**Comment by krcarriere** [comment]
Perhaps, but even with specifying mod2vals:

jtools::interact_plot(model3, pred = "wt",
                      modx = "hp", mod2="drat", jnplot="true",
                      x.label="X Label", y.label="Y Label",
                      legend.main="Legend Title", mod2vals = "terciles", mod2.labels = c("test1","test2", "test3"))

Still doesn't change anything.

**Comment by jacob-long** [comment]
I should have been clearer about what I meant. The bug is that when using one of the presets (like "terciles"), the `mod2.labels` argument is ignored.

**Comment by krcarriere** [comment]
Thank you!
