### ISSUE TITLE
saving johnson neyman plot

### ISSUE THREAD

**Issue by ae07** [jacob-long/jtools#32]
Hello! I am trying to save a a JN plot in high resolution for a poster using ggsave  but I saw that this error occurs when trying to use ggsave:

Error in UseMethod("grid.draw") : 
  no applicable method for 'grid.draw' applied to an object of class "johnson_neyman"

Do you recommend another way to save the plot so it is not blurry for the poster?

My other question is whether it is possible to modify the JN plots using theme()? I am trying to make the numbers of the axis in Arial and bolded. I am able to do so for interact_plot but not for the JN plots.

Thank you!

**Comment by jacob-long** [comment]
I think the problem here is that the `johnson_neyman` object returned by the function is not a `ggplot` object. The plot is actually just one part of the `johnson_neyman` object, which you can access via `$plot`. 

For instance, 

```r
states <- as.data.frame(state.x77)
states$HSGrad <- states$`HS Grad`
fit <- lm(Income ~ HSGrad + Murder * Illiteracy, data = states)
## Saving the johnson_neyman object
jn <- johnson_neyman(model = fit, pred = Murder, modx = Illiteracy)
## Accessing the plot
jn$plot
## Saving the plot
ggsave(jn$plot)
```

Should work.
