### ISSUE TITLE
Formula environment causing error

### ISSUE THREAD

**Issue by ngreifer** [jacob-long/jtools#34]
See this example:
```
X <- rnorm(100)
Y <- rnorm(100)
F <- function(f) summ(glm(f))
F(Y ~ X)

## Error: object of type 'symbol' is not subsettable 
```
The traceback is:
```
10. notnull(x$formula) 
9. formula.default(object, env = baseenv()) 
8. formula(object, env = baseenv()) 
7. as.formula(old) 
6. update.formula(call$formula, formula) 
5. j_update(object, formula = form, weights = .weights, offset = .offset, 
    data = frame) 
4. pR2(model) 
3. summ.glm(glm(f)) 
2. summ(glm(f)) 
1. F(Y ~ X) 
```
I think this is occurring because the environment in which you are evaluating the formula when decomposing the `glm` object is not the same environment with the data. Note that this occurs even when a data set is included in `glm`. This isn't a huge problem but points to a possible underlying issue. The way around it is to pass the `glm` object to `F()` rather than just the formula.

**Comment by jacob-long** [comment]
Programmatic model updating is a bear. I think I've fixed it.

**Comment by ngreifer** [comment]
Yup! Thank you :)
