### ISSUE TITLE
Add sim_slopes to have label functionality

### ISSUE THREAD

**Issue by krcarriere** [jacob-long/jtools#35]
Following the vignette:
library(survey)
library(jtools)
data(api)
dstrat<-svydesign(id=~1,strata=~stype, weights=~pw, data=apistrat, fpc=~fpc)
regmodel3 <- survey::svyglm(api00 ~ avg.ed * growth * enroll, design = dstrat)
sim_slopes(regmodel3, pred = growth, modx = avg.ed, mod2 = enroll,
           jnplot = TRUE, mod2.labels=c("test", "test1", "test2"))

Would be great to be able to label those as well! :) Sorry for all the issues, just trying to use your package for some visualizations for publications and want it to be clean looking!

**Comment by jacob-long** [comment]
Are you thinking the labeled output should look like this?

`While enroll (2nd moderator) = 1037.51 (test2)`

instead of

`While enroll (2nd moderator) = 1037.51 (+ 1 SD)`

**Comment by jacob-long** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [sim_slopes labels](https://trello.com/c/amXEiFRA/9-simslopes-labels)

**Comment by krcarriere** [comment]
Ahh. I realize what I asked wasn't clear. 

I'm trying to figure out how to get additional commands onto the jnplot=TRUE command part. So, when it's plotted, being able to edit the plot itself. (Changing "Slope of growth" to "Slope of Growth", "enroll = + 1 SD" to "Enrolled Above 1 SD", etc). 

Which seems like something brought up in this issue: 
https://github.com/jacob-long/jtools/issues/15

So maybe I just need to dig into the jn objects in the sim_slopes function.
