### ISSUE TITLE
Install had non-zero exit status

### ISSUE THREAD

**Issue by jonathon-heale** [jacob-long/jtools#38]
Hello, I installed 'jtools' and it worked once, but when installing 'ggstance' to use the plot_summ command, 'jtools' will no longer load and I received error as: "Warning in install.packages :   installation of package ‘jtools’ had non-zero exit status"  

I have also tried installing with devtools as: devtools::install_github("jacob-long/jtools")  and still receive the same error!

Any help you can provide is greatly appreciated!

Jon

**Comment by jacob-long** [comment]
That's bizarre. Is there any additional output you can share (e.g., any error messages that came up when the installation of `ggstance` failed)?

Might also be useful to know what version of R you're using and whether you're using Windows/Mac/Linux.

**Comment by jonathon-heale** [comment]
Jacob, 

It appears something went wrong with 'rlang' on R-Studio v3.4.2 on Windows 64-bit. An uninstall and update of 'rlang' fixed everything. 

Cheers, 
Jon
