### ISSUE TITLE
Possibly update export_summs for huxtable 1.0.0

### ISSUE THREAD

**Issue by hughjonesd** [jacob-long/jtools#5]
Very glad to have a consumer of my code! Huxtable 1.0.0 has just come out, and there are a few [changes](github.com/hughjonesd/huxtable/news.md) to the huxreg API which you might want to be aware of.

 Cheers, David

**Comment by jacob-long** [comment]
All fixed up now that huxtable 1.0.0 binary is available for Windows users. jtools update heading to CRAN now.
