### ISSUE TITLE
Adaptation of `plot_summs` to logistic regression - show odds ration instead of estimates

### ISSUE THREAD

**Issue by adisarid** [jacob-long/jtools#51]
Lately, I've used the function to plot logistic regression, but instead of using the estimates themselves, I wanted to use the odds ratio (i.e., `exp(coef)`) which is some sense is reasonable when you want to illustrate "the meaning" of coefficients and not the coefficients.

This required me to manually change the labels of the x-axis using breaks and labels in `scale_x_continuous(...)`. Perhaps this is a reasonable feature to add.

**Comment by jacob-long** [comment]
Hello Adi! I'm happy to report this feature is already implemented via the `exp` argument (so `plot_summs(model, exp = TRUE)` should give you what you want).

**Comment by eiovidal** [comment]
First, thank you so much for creating the jtools package! 
Second, is there a way for the scale of plot_summs plots from glm models to be set as a log scale, so that the exponentiated confidence intervals will be symmetric?
