### ISSUE TITLE
Allow scale_mod options in summ

### ISSUE THREAD

**Issue by ngreifer** [jacob-long/jtools#54]
I'd like it if `summ()` could have the argument `binary.inputs` that is in `scale_mod` so I can choose how I want to scale my binary predictors. As of now, I don't think it's possible to scale them in `summ`, though it is possible in `scale_mod`, which seems a little asymmetrical.

**Comment by jacob-long** [comment]
Thanks Noah! What I've done is just pass any arguments not formally documented by `summ()` to `scale_mod()` or `center_mod()` when `scale` or `center` is `TRUE`. I should probably consider dropping the documentation for the `n.sd` argument in `summ()` and making it available in this same backdoor way.
