### ISSUE TITLE
Extract r squared?

### ISSUE THREAD

**Issue by bshor** [jacob-long/jtools#56]
summ() works great for my svyglm models, but I'd like to extract the R^2 statistics which I see printed to the console but I can't seem to find in the object.

**Comment by jacob-long** [comment]
There are two ways:

```r
library(survey)
data(api)
dstrat <- svydesign(id = ~1, strata =~ stype, weights =~ pw,
                      data = apistrat, fpc =~ fpc)
regmodel <- svyglm(api00 ~ ell * meals, design = dstrat)

attr(summ(regmodel), "rsq")
```

or 

```r
broom::glance(summ(regmodel))$r.squared
```

`glance()` might be more reliable in case I ever change what the attribute is called, but either should be fine.

**Comment by bshor** [comment]
Great! Thanks.

**Comment by eredmiles** [comment]
I'm trying to use this solution for "arsq" but while the "rsq" solution works perfectly, I get NA when I substitute "arsq" despite the fact that an adjusted R2 value is displayed in the full summ print out.
