### ISSUE TITLE
Vignette for LaTeX?

### ISSUE THREAD

**Issue by bshor** [jacob-long/jtools#57]
I'm trying to produce a regression table for use in creating a paper with LaTeX. My model fits are all inside a list, which export_summs() deals with just fine. Help tells me to look up the documentation for latex tables with the huxtable package, but it is [not straightforward](https://hughjonesd.github.io/huxtable/huxtable.html#creating-a-regression-table) to see what to do there at all. Is it possible to have a vignette that illustrates the export of LaTeX regression tables (including those with multiple models)?

**Comment by jacob-long** [comment]
I think the source of confusion may be that the documentation is made with the assumption that the document is being created with RMarkdown. 

If you want the raw LaTeX output, try this:

```r
library(survey)
data(api)
dstrat <- svydesign(id = ~1, strata =~ stype, weights =~ pw,
                      data = apistrat, fpc =~ fpc)
regmodel <- svyglm(api00 ~ ell * meals, design = dstrat)

huxtable::print_latex(export_summs(regmodel))
```

Gives 
```latex
  \providecommand{\huxb}[2]{\arrayrulecolor[RGB]{#1}\global\arrayrulewidth=#2pt}
  \providecommand{\huxvb}[2]{\color[RGB]{#1}\vrule width #2pt}
  \providecommand{\huxtpad}[1]{\rule{0pt}{\baselineskip+#1}}
  \providecommand{\huxbpad}[1]{\rule[-#1]{0pt}{#1}}

\begin{table}[h]
\centering
\begin{threeparttable}
\begin{tabularx}{0.5\textwidth}{p{0.25\textwidth} p{0.25\textwidth}}


\hhline{>{\huxb{0, 0, 0}{0.8}}->{\huxb{0, 0, 0}{0.8}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}c!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\centering \huxbpad{4pt}} &
\multicolumn{1}{c!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\centering Model 1\huxbpad{4pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{255, 255, 255}{0.4}}->{\huxb{0, 0, 0}{0.4}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedright (Intercept)\huxbpad{4pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedleft 836.62 ***\huxbpad{4pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedright \huxbpad{4pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedleft (10.99)~~~\huxbpad{4pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedright ell\huxbpad{4pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedleft -1.69~~~~\huxbpad{4pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedright \huxbpad{4pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedleft (1.01)~~~\huxbpad{4pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedright meals\huxbpad{4pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedleft -3.32 ***\huxbpad{4pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedright \huxbpad{4pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedleft (0.28)~~~\huxbpad{4pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedright ell:meals\huxbpad{4pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedleft 0.02~~~~\huxbpad{4pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedright \huxbpad{4pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedleft (0.01)~~~\huxbpad{4pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{255, 255, 255}{0.4}}->{\huxb{0, 0, 0}{0.4}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedright N\huxbpad{4pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedleft 200~~~~~~~\huxbpad{4pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedright R2\huxbpad{4pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{4pt}\raggedleft 0.66~~~~\huxbpad{4pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.8}}->{\huxb{0, 0, 0}{0.8}}-}
\arrayrulecolor{black}

\multicolumn{2}{!{\huxvb{0, 0, 0}{0}}p{0.5\textwidth+2\tabcolsep}!{\huxvb{0, 0, 0}{0}}}{\parbox[b]{0.5\textwidth+2\tabcolsep-4pt-4pt}{\huxtpad{4pt}\raggedright  *** p $<$ 0.001;  ** p $<$ 0.01;  * p $<$ 0.05.\huxbpad{4pt}}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}
\end{tabularx}\end{threeparttable}


\end{table}
```

You may need to add some `\usepackage` commands to your preamble for this to work.

**Comment by bshor** [comment]
Thanks for getting back to me. My workflow uses "old school" LaTeX, either with a local editor or one of the new online ones, so I need LaTeX regression tables.   

The problem with this solution is that we are leaving the nice world of export_summs. So we're not getting the model and coefficient renaming, etc. Any way of getting export_summs to push out LaTeX itself?

**Comment by jacob-long** [comment]
This is tricky — I consider LaTeX tables to be a nightmare! Let me know if you get a better result doing this in R:

```r
my_table <- export_summs(my_model1, my_model2)
huxtable::width(my_table) <- 0.8 # any number between 0 and 1 as a percentage of page width
huxtable::print_latex(my_table)
```

I *think* what's happening is that `huxtable` tries to automatically determine a width for the table (or it just has a narrow default) and that is making LaTeX trying to fit into a small horizontal space, which is why it is offset to the right so much. Since it can't fit, it just runs off to the right. If I'm right, by setting the width on the `huxtable` object you should get it moving to the left. 

If the table is actually wider than the entire page, that's where things get tricky — maybe you'll need to put it in a landscape orientation page environment. Maybe shrinking the font size would be an option too. We can cross that bridge when we get there...

**Comment by bshor** [comment]
They are, but not all of us have switched to the Markdown world yet, so we still do LaTeX!

This kludge is helpful and I needed to tweak each table's width, but it works. Thanks!

**Comment by bshor** [comment]
Ok, so now I'd like to adjust things like font size (default is too big for beamer slide) and adding rows  (like Demographics ... Y N Y N etc).

**Comment by jacob-long** [comment]
Almost lost track of this issue. For your latest question, I think the `huxtable` documentation should be useful.

**Comment by anguyen1210** [comment]
> Thanks for getting back to me. My workflow uses "old school" LaTeX, either with a local editor or one of the new online ones, so I need LaTeX regression tables.
> 
> This solution does work, but in a standard LaTeX article, looks strangely shifted to the right and down. See attached.
> 
> ![image](https://user-images.githubusercontent.com/468070/55890290-118a7300-5b78-11e9-81d8-d661915e8a22.png)

This is my exact issue as well.  When I render my huxtable reg table in rmarkdown to pdf, no matter what I set the  `width()` argument to, it still pushes the table off the the right beyond the page margin.  I have a table with 8 columns, which should fit within the width of the page, but even when I make table with 3 or 4 columns, I can see that there is all this extra white space to the left of the table, and I can't figure out why.
