### ISSUE TITLE
Effect_plot question

### ISSUE THREAD

**Issue by MbaliNen** [jacob-long/jtools#60]
Hello,
I would like to overlay three different plots I created with effect_plot, predicting the effect of three different glms. Is it possible? I am trying to add one effect_plot to the other and I obtain: 'I don't know how to add effect_plot.....to a plot' (me neither my dear R). 
Can anybody help?

**Comment by jacob-long** [comment]
I'd say yes, this is possible, although it is not the most straightforward thing. There are two basic approaches to dealing with this kind of issue.

### Option 1

One of them is to get the raw data used to make the plots via `make_predictions()`. Let's say you have two models, called `glm1` and `glm2` and you have predictor `x` and outcome `y` that you're interested in for both of them. I'll generate the predicted data for both models, add a column labeling which model it is, then bind those two data frames together, and then finally generate a facet plot from those combined data.

```r
# assuming you already have fitted model objects called glm1 and glm2 with a predictor called x 
# and outcome called y
library(jtools)
library(dplyr) # for combining the data frames
data1 <- make_predictions(glm1, pred = x)
data1$model <- "Model 1"
data2 <- make_predictions(glm2, pred = x)
data2$model <- "Model 2"

cdata <- bind_rows(data1, data2)

library(ggplot2)
ggplot(cdata, aes(x = x, y = y)) + geom_path() + facet_wrap(~ model)
```

I think that would work, although I haven't actually run the code to make sure I didn't make a silly mistake. The output would need some care and feeding, like dealing with the theme and possibly some labels.

### Option 2

Maybe that seems like a lot of work or you don't want to have to deal with `ggplot2` syntax. You can download an in-development package called `patchwork` that would work really well for this, I think. Note that it is not yet on CRAN. To get it, use `devtools::install_github("thomasp85/patchwork")`. The package lets you combine separate plots by just adding them together like you wanted to do.

```r
library(patchwork)
effect_plot(glm1, pred = x) + effect_plot(glm2, pred = x)
```

You can see some more basic documentation at the [patchwork Github page](https://github.com/thomasp85/patchwork).

**Comment by MbaliNen** [comment]
Thanks a lot Jacob!

I have already tried the first way but unfortunately my models contain a
different number of data, so I cannot bind them together to create a
dataframe.

Right now I created 2 data frames (pd and zd) with the results of the
predictions of 2 models, and plotted the needed variable and CI at 95% like
this:

###Plot
ggplot() +
  geom_line(data=pd, aes(xs, p.est), color='green') +
  geom_line(aes(xs,p.lcl), colour = "turquoise") +
  geom_line(aes(xs,p.ucl), colour = "turquoise") +
  geom_line(data=zd, aes(z, z.p.est), color='red') +
  geom_line(aes(z,z.p.lcl), colour = "orange") +
  geom_line(aes(z,z.p.ucl), colour = "orange")

It works, but I need to improve the aestethics.

Thanks a lot for the patchwork suggestion, I will try it straight away!

Have a good day, regards

Elena Mariotti

MSc Candidate

School of Animal, Plant and Environmental Sciences

University of the Witwatersrand

Johannesburg


Il giorno sab 11 mag 2019 alle ore 06:15 Jacob Long <
notifications@github.com> ha scritto:
