### ISSUE TITLE
plot_coefs(): point size and stroke

### ISSUE THREAD

**Issue by luismmontilla** [jacob-long/jtools#61]
I'm trying to increase the point size with a plot_coefs(). What would be the best approach to this?

**Comment by jacob-long** [comment]
I'm not seeing any good way to do this for the end user. I'll have to explore  whether I want to add more arguments to `plot_coefs()` or should just offer an easier way for people to get the data "cleaned" in the way that `plot_coefs()` does under the hood and then let the end user make the calls to `ggstance::geom_pointrangeh()`, etc.

**Comment by ngreifer** [comment]
If you don't want to add a million arguments you could use `...` and just say the arguments are passed down to `geom_pointrangeh()`. I do this with `love.plot()` and `bal.plot()` in `cobalt` for some elements that would be hard for the user to change otherwise.

**Comment by jacob-long** [comment]
I went ahead and added this option in bef141eb8c0e549effd97f6249fd85f81a3cda5b. Thanks for the input!
