### ISSUE TITLE
effects from 2 models in 1 plots

### ISSUE THREAD

**Issue by daisyburr** [jacob-long/jtools#62]
Hi Jacob, 

Is there a way to plot the effects of two models on one plot? For example, I have one model that is positive_affect ~ age, and one that is positive_affect~age*well-being. Is there a way to overlay the effect of age with and without controlling for well-being in one plot?

Thanks, 
Daisy

**Comment by jacob-long** [comment]
The short answer is there's no super simple way to do it. Without going into the full details, I think the best strategy would be to use the data from `make_predictions()` for both models, `dplyr::rbind()` those data frames together, and then use `ggplot2` to make the plot with a `group = model` aesthetic argument.

I may look into automating that process in a new function, though.

**Comment by oalavijeh** [comment]
Dear Jacob, 

Did you ever do this? I have fitted two separate GLM models on two groups of patients with exactly the same coefficents and would like to overlay the two effect plots over each other. 

Many thanks
