### ISSUE TITLE
Input as list for plot_summs

### ISSUE THREAD

**Issue by zx8754** [jacob-long/jtools#64]
Relevant SO post:
 - [Is it possible to automate plot_summs with a list of models?](https://stackoverflow.com/q/56439893/680068)

```R
library(jtools)

# example models
tmp <- list(m1 = lm(mpg ~ cyl + disp, data = mtcars),
            m2 = lm(mpg ~ cyl + hp, data = mtcars))
```

This works:

```R
plot_summs(tmp$m1, tmp$m2)
```

Ideally, should work with a list input, as:

```R
plot_summs(tmp)
```

Workaround suggested at SO:

```R
do.call(plot_summs, setNames(tmp, NULL))
```

**Comment by jacob-long** [comment]
Thanks for letting me know about this. I had planned to allow lists as input, had done it for another function, and didn't realize I hadn't for this one.
