### ISSUE TITLE
export_summs robust expects logical

### ISSUE THREAD

**Issue by undestu** [jacob-long/jtools#65]
I am trying to use export_summs to print out the results of an ordinary linear regression with HC1 robust standard errors...

`results = lm(Sepal.Width ~ Species + Sepal.Length, iris)`
`# summ(results, robust="HC1") # for reference`
`export_summs(results, robust="HC1")`

... which returns the following errors:

`Error in if (scale == TRUE) { : missing value where TRUE/FALSE needed`
`In addition: Warning message:`
`In all(robust) : coercing argument of type 'character' to logical`

When I input `export_summs(results, robust=TRUE)`, it gives me the HC3 errors. I also tried to first input `set_summ_default(robust="HC1")` but this doesn't get the HC1 errors too.

When I input `export_summs(results, robust.type="HC1")`, I am able to get HC1 and the following (harmless) errors:

`Warning messages:`
`1: The robust.type argument is deprecated. Please specify the type as the value for the 'robust' argument instead. `
`2: The robust.type argument is deprecated. Please specify the type as the value for the 'robust' argument instead. `

If it helps, I'm getting this issue with jtools v.2.0.1 on R v.3.6.0 and v3.5.2.

**Comment by jacob-long** [comment]
Thank you for reporting!

**Comment by albertostefanelli** [comment]
Hi, Thanks for the package. 
The error above reported still persists. 
Using `robust="HC1"` in the `export_summs()` results in the following error message 

```
Error in if (scale == TRUE) { : missing value where TRUE/FALSE needed                       
In addition: Warning message:
In all(robust) : coercing argument of type 'character' to logical 
```
I am using jtools_2.0.1 with R version 3.6.1 (2019-07-05)
