### ISSUE TITLE
is it possible to add a feature plot_summs that allows sorting (in descending or ascending order)?

### ISSUE THREAD

**Issue by ghost** [jacob-long/jtools#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe any alternatives or other implementations that you might know of**

**Additional context**

**Comment by jacob-long** [comment]
It's possible...are you thinking of sorting by the value of the coefficients, similar to the plots you might see in a meta-analysis?

**Comment by PacoMax** [comment]
You have to reorder your data before using "plot_summs" function. For example, you could use "rev()" to invert the order.
