### ISSUE TITLE
Argument "at" in effect_plot

### ISSUE THREAD

**Issue by pascalsiemsen** [jacob-long/jtools#68]
Thanks a lot for the package. Super nice graphs with a minimum of effort - that is nice.
I ran a logistic regression and find the effect plot really helpful. As I understand it, the mean for concinnous and the reference category for categorical variables is used. 

I wanted to set the values of some control variables with the argument "at" and created the named list. I do get the same results though (the variables I want to change are factor btw) and it seems "at" is ignored.

```r
data(bacteria)
l_mod <- glm(y ~ trt + week, data = bacteria, family = binomial)
summ(l_mod)

effect_plot(l_mod, pred = trt, centered = "none", interval = TRUE, y.label = "% testing positive")
ex  <- list(week = 11)
effect_plot(l_mod, pred = trt, centered = "none", at = ex, interval = TRUE, y.label = "% testing positive")
```

**Comment by jacob-long** [comment]
Looks like this was fixed at some point in the years since you shared the bug. Thanks for reporting.
