### ISSUE TITLE
Confusing note when using export_summs() 

### ISSUE THREAD

**Issue by mattwilsonky** [jacob-long/jtools#73]
Hi, first off I love the package, thanks for all your work. One issue I am having, however, is that when I use export_summs() with 'scale = FALSE', there is still a note at the bottom of the table that reads "All continuous predictors are mean-centered and scaled by 1 standard deviation." It seems the code is working in that it is indeed not scaling the regressors; the issue is that the message still appears, which is mildly confusing.

**Comment by jacob-long** [comment]
It appears this is no longer occurring in the soon-to-be-uploaded version, so I'm going to assume this was unintentionally fixed somewhere along the way.
