### ISSUE TITLE
R export_summs generating error with dropped fixed effects

### ISSUE THREAD

**Issue by nhilgerczi** [jacob-long/jtools#74]
First of course thank you so much for this great package, really value it and use it all the time. 

I am running a fixed effects regression with felm(). Some of the fixed effects are collinear and get dropped,  but that's ok they're nuisance parameters. I can display the results with summary() and they look good and just show NA for those coefficients on dropped fixed effects. But when I try to display the key coefficient of interest in export_summs(), I get this error:

Warning message in base$std.error[!is.na(base$std.error)] <- x$coeftable[, "S.E."]: “number of items to replace is not a multiple of replacement length”Warning message in base$statistic[!is.na(base$statistic)] <- x$coeftable[, stat_col]: “number of items to replace is not a multiple of replacement length”Warning message in base[["p.value"]][!is.na(base$statistic)] <- x$coeftable[, "p"]: “number of items to replace is not a multiple of replacement length”

Not only that, but the call to export_summs() doesn't fail, it just hangs indefinitely in Jupyter and then nothing works and I have to restart the kernal.

Note export_summs() is working fine for regressions without any dropped coefficients.

Thanks for your help. Also posted on StackExchange: https://stackoverflow.com/questions/58384863/r-export-summs-generating-error-with-dropped-fixed-effects

```r
# insert reprex here
```

**Comment by nhilgerczi** [comment]
I suspect this is happening because for the dropped fixed effects, the estimates are NA but the SE is 0.0000.

**Comment by jacob-long** [comment]
Unfortunately the StackExchange post has disappeared so I'm not able to replicate the issue (yes, I know this is MY fault for taking years to get to this 😄 ). There's a chance the issue has been solved in the meantime by other changes implemented, specifically in the recent commit b5d022c28c1f734d0246100b7652aeca1b3b40df. So I'm going to assume the next release fixes this until I hear otherwise.
