### ISSUE TITLE
no applicable method for 'summ' applied to an object of class "coxph"

### ISSUE THREAD

**Issue by winterwang** [jacob-long/jtools#76]
Hi, maybe I missed something, I tried to print result from a Cox regression object and it seems that it is not supported yet:

```
Error in UseMethod("summ") : 
  no applicable method for 'summ' applied to an object of class "coxph"
```

is this a future feature or else?

Thanks!

**Comment by jacob-long** [comment]
Definitely a potential future supported model. #16
