### ISSUE TITLE
export_summs does not work with robust arguments

### ISSUE THREAD

**Issue by martinzuba** [jacob-long/jtools#77]
The export_summs function produces the error 
`Error in if (scale == TRUE) { : missing value where TRUE/FALSE needed`
when a `robust` argument is given.

Reproducible example:
`lm(speed ~ dist, data = cars) %>% summ(robust = "HC3") # works as expected`

`lm(speed ~ dist, data = cars) %>% export_summs(robust = "HC1") #error`

It seems to work with `robust = TRUE` but then `scale` seems to be set to `TRUE` no matter what is specified.

**Comment by jacob-long** [comment]
I'm not able to replicate this issue. I'm thinking it must have been inadvertently fixed at some point.
