### ISSUE TITLE
Select variables in plot_summs to show

### ISSUE THREAD

**Issue by HugoGit39** [jacob-long/jtools#78]
**Is your feature request related to a problem? Please describe.**

I am wondering if there is a way to exclude variables to show in plot_summs. Hereby the x-axis can be in mor detailed numbers than if these variables are shown. I thought the omit.coeeficient was the solution bit its not. Would be great!

**Describe the solution you'd like**
Only select certain variables not all.

**Comment by HugoGit39** [comment]
Nobody knows?

**Comment by jacob-long** [comment]
Hi,

You should be able to accomplish this using the `coefs` or `omit.coefs` arguments if I understand you correctly. 

If you pass a vector of coefficients you don't want included to `omit.coefs`, they should not show up. For instance, if I do not want the plot to show the variables `x` and `z`, then I would use `omit.coefs = c("x", "z")`
