### ISSUE TITLE
Group graphs by model instead of independent variables

### ISSUE THREAD

**Issue by husky114** [jacob-long/jtools#80]
Hi! This has been a game changer package!

Is there any way to stack the plot lines so that, using your example, we group them by Models 1 and 2, and not Frost, Illiteracy and Murder? So all Model 1 coefficients (for Frost, Illiteracy, and Murder) would be stacked/clustered together, then followed by Model 2. I'm trying to plot 5-ish variables by 3 treatment groups, so I think stacking them by variable would be easier to distinguish treatment effects from each other. Thanks so much!

**Comment by jacob-long** [comment]
I'm sorry, I'm not sure I understand what you're looking for. Would this mean that the color coding is by variable and the Y-axis separates the models?
