### ISSUE TITLE
simple_slopes error when using svyglm with bootstrapped standard errors

### ISSUE THREAD

**Issue by markhwhiteii** [jacob-long/jtools#84]
I hate to not offer a reprex, but I unfortunately cannot share the data.

Using the `srvyr` package to create the survey object:

```
sdat <- dat %>% 
  as_survey(weight = weight) %>% 
  as_survey_rep(type = "bootstrap", replicates = 5000)
```

Then, I fit a model using `svyglm`:

```
mod1 <- survey::svyglm(y ~ z1 * x * z2, sdat)
```

And probe the interaction with `simple_slopes`:

```
sim_slopes(mod1, pred = "x", modx = "z1", mod2 = "z2")
```

This returns:

```
Error in pwt[i] : invalid subscript type 'list'
```

Does the package not handle bootstrapped `svyglm` objects? If I don't use bootstrapping for the standard errors, I get a result just fine.

**Comment by jacob-long** [comment]
Thanks for reporting, @markhwhiteii. I've "transferred" this issue to the `jtools` package repository because I think that's where the failure is actually occurring. The basic problem here is that I've never tested any functionality with replicate weights. I have some fixes incoming...
