### ISSUE TITLE
(Simple) Doubt =)

### ISSUE THREAD

**Issue by gosvnavarro** [jacob-long/jtools#87]
Hey there,

I'm using the function 'plot_summs' to graphically show the "difference" between nested models that I have, however, when I plot the models I don't understand which values from the independent variables that the function is grabbing in order to plot in the graph; the x-axis title is "Estimate" but which estimate(?), because I've tried to find from where those values are coming from (estimated values of the lm() for example) but I wasn't successful. I tried to look online as well for materials using the package but I didn't found anything explaining from where these values come from.

Could you, please, explain what is this "Estimate" means and from where it comes from?

**Comment by jacob-long** [comment]
The "estimate" in this case is the value of the regression coefficient rather than a value coming from the data. It is basically a graphical way of looking at `summary(model)`.
