### ISSUE TITLE
General Question- effect_plot for marginal effects?

### ISSUE THREAD

**Issue by mickayla32** [jacob-long/jtools#90]
I apologize if this is a silly question, but I'm having trouble finding the answer to it anywhere online, and am new to R and stats in general.  I'm wondering if the output of `effect_plot()` are the plotted marginal effects of a model/ if it is the same output as the function `plot_model(type = "pred")` from the package `sjPlot`?

**Comment by jacob-long** [comment]
Yes, `effect_plot()` produces marginal effects as they are generally understood. I'm fairly certain it produces an equivalent output to the `sjPlot` function you mentioned.
