### ISSUE TITLE
Better documentation for "cluster"

### ISSUE THREAD

**Issue by mattysimonson** [jacob-long/jtools#93]
In the `summ` functions, it's not clear from the documentation that one must set `robust` = HC1, HC2, or HC3 in order to use the `cluster`. If you input `HC4` you get a warning telling you to use a lower HC, but if you don't realize you need to set `robust` in the first place, then `cluster` will fail silently and you'll only know it wasn't invoked if you compared the results to a non-clustered model. It would be great if you could add a line to the documentation that says this explicitly, add a warning or error when `cluster` is used without an appropriate `robust` setting, and also add an example that uses cluster to the vignettes or examples. Thanks!

**Comment by jacob-long** [comment]
Great suggestion, thank you!

**Comment by mattysimonson** [comment]
Thanks!
