### ISSUE TITLE
Renaming coefficient in plot for glm in plot_summs

### ISSUE THREAD

**Issue by IsadoraBM** [jacob-long/jtools#94]
Since glm() does not accept tidy names that use `contain space` structure, it is impossible to rename a variable before running the model. Is it possible to add a feature that lets you rename the estimate coefficients within the plot?

**Comment by jacob-long** [comment]
Yes, you can do this already!

See the `coefs` argument documentation:

> If you'd like to include only certain coefficients, provide them as a vector. If it is a named vector, then the names will be used in place of the variable names. See details for examples. Default: NULL

So 

```r
plot_summs(fit1, coefs = c("My pretty new name 1" = ugly_name_1, "My pretty new name 2" = ugly_name_2))
```

Would achieve a result like what you're looking for.
