### ISSUE TITLE
Error: significance stars not printed because tidy() does not return p values for models of class data.frame;

### ISSUE THREAD

**Issue by mmaloof612** [jacob-long/jtools#98]
Hello! I am using export_summs to produce a table of 4 models. The table produces beautifully, but without significance stars. R gives me this error: 

Warning messages:
1: In FUN(X[[i]], ...) :
  tidy() does not return p values for models of class data.frame; significance stars not printed.
2: In FUN(X[[i]], ...) :
  tidy() does not return p values for models of class data.frame; significance stars not printed.
3: In FUN(X[[i]], ...) :
  tidy() does not return p values for models of class data.frame; significance stars not printed.
4: In FUN(X[[i]], ...) :
  tidy() does not return p values for models of class data.frame; significance stars not printed.

The models are all ordered logistic regressions using polr, same models with different DVs

Example code/model: 
model2= polr(as.factor(v1) ~ v2 + v3+ v4, data = data, Hess = TRUE, method="logistic")
export_summs(model1, model2, model3, model4, scale = TRUE)

How can I add the significance stars to the model to make the table easily legible for all readers? Thank you!

**Comment by jacob-long** [comment]
Hmm, I'm thinking this is an issue with the [`huxtable`](https://github.com/hughjonesd/huxtable) package. It has a similar function called `huxreg()`, which `export_summs()` uses, and it has the same problem.

**Comment by jacob-long** [comment]
Well, the error message is confusing but the root of the issue here is that `polr()` does not provide *p* values! I may add `polr()` support to `jtools` at some point to give those *p* values, but I'm not sure when that will happen.
